using Microsoft.EntityFrameworkCore.Migrations;

namespace backend.Migrations
{
    public partial class added_autogenerated_IDs : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {

        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
