# This is a sample build configuration for .NET Core.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: mcr.microsoft.com/dotnet/core/sdk:3.1


pipelines:
  default:
    - step:
        caches:
          - dotnetcore
        script: # Modify the commands below to build your repository.
          - cd backend/backend/
          - export PROJECT_NAME=backend.csproj
          - dotnet restore 
          - dotnet build $PROJECT_NAME
          - dotnet publish $PROJECT_NAME --self-contained --runtime win-x64 --configuration Debug
          - zip -j site.zip /opt/atlassian/pipelines/agent/build/backend/bin/Debug/netcoreapp3.0/win-x64/publish/*  -x aws-windows-deployment-manifest.json
          - zip -r -j application.zip site.zip /opt/atlassian/pipelines/agent/build/backend/bin/Debug/netcoreapp3.0/win-x64/publish/aws-windows-deployment-manifest.json 
          - pipe: atlassian/aws-elasticbeanstalk-deploy:0.6.2
            variables:
             AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
             AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
             AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
             APPLICATION_NAME: $APPLICATION_NAME
             ENVIRONMENT_NAME: $ENVIRONMENT_NAME
             ZIP_FILE: 'application.zip'
