name: .NET Core

on:
  push:
    branches: [ master, release/* ]
  pull_request:
    branches: [ master, release/* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Change Directory
      run: cd backend
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: cd backend && dotnet restore
    - name: Build
      run: cd backend && dotnet build --configuration Release --no-restore
    - name: Test
      run: cd backend && dotnet test --no-restore --verbosity normal
	- name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mcts-service'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_dbfc43d5184d4c91b0dd37ff026e45b0 }}
        package: ${{env.DOTNET_ROOT}}/myapp 
